#  Procesador EDA

In [1]:
import sys
sys.path.append("..")  # permite acceder a cargaDatos/, eda/, clases/

### Importación de módulos carga datos y procesador eda

In [2]:
from cargaDatos.cargador_datos import CargadorDatos
from eda.procesador_eda import ProcesadorEDA

### Carga del dataset original

In [3]:
loader = CargadorDatos("../data/raw/premier.csv")
df = loader.cargar_csv()

df.head()

 Encoding detectado: utf-8
 Separador detectado: ','
 CARGA DE DATOS REALIZADA
 Archivo: ../data/raw/premier.csv
 Filas cargadas: 4270
 Columnas: 33

 Porcentaje de nulos por columna:
Player                    0.00
Team                      0.00
#                         0.00
Nation                    0.00
Position                  0.00
Age                       0.00
Minutes                   0.14
Goals                     0.00
Assists                   0.00
Penalty Shoot on Goal     0.00
Penalty Shoot             0.00
Total Shoot               0.00
Shoot on Target           0.00
Yellow Cards              0.00
Red Cards                 0.00
Touches                   0.00
Dribbles                  0.00
Tackles                   0.00
Blocks                    0.00
Expected Goals (xG)       0.00
Non-Penalty xG (npxG)     0.00
Expected Assists (xAG)    0.00
Shot-Creating Actions     0.00
Goal-Creating Actions     0.00
Passes Completed          0.00
Passes Attempted          0.00
Pass Completion %         1.08
Progressive Passes        0.00
Carries                   0.00
Progressive Carries       0.00
Dribble Attempts          0.00
Successful Dribbles       0.00
Date                      0.00
dtype: float64

 Nulos totales: 52 de 140910 celdas
 Porcentaje total de nulos: 0.04%

,Player,Team,#,Nation,Position,Age,Minutes,Goals,Assists,Penalty Shoot on Goal,...,Goal-Creating Actions,Passes Completed,Passes Attempted,Pass Completion %,Progressive Passes,Carries,Progressive Carries,Dribble Attempts,Successful Dribbles,Date
0,Bruno Fernandes,Manchester United,8,POR,"FW,AM",29-343,90.0,0,0,0,...,0,43,60,"71,7",6,50,7,1,1,2024-08-16
1,Marcus Rashford,Manchester United,10,ENG,LW,26-290,90.0,0,0,0,...,0,22,30,"73,3",2,34,2,6,0,2024-08-16
2,Amad Diallo,Manchester United,16,CIV,RW,22-036,NaN,0,0,0,...,0,28,33,"84,8",1,22,0,1,1,2024-08-16
3,Alejandro Garnacho,Manchester United,17,ARG,RW,20-046,30.0,0,1,0,...,1,10,11,"90,9",0,11,2,2,0,2024-08-16
4,Mason Mount,Manchester United,7,ENG,AM,25-219,60.0,0,0,0,...,0,11,15,"73,3",1,16,0,2,0,2024-08-16

### Tipos de datos

In [4]:
print("Filas y columnas:", df.shape)
df.dtypes

Filas y columnas: (4270, 33)

Player                     object
Team                       object
#                           int64
Nation                     object
Position                   object
Age                        object
Minutes                   float64
Goals                       int64
Assists                     int64
Penalty Shoot on Goal       int64
Penalty Shoot               int64
Total Shoot                 int64
Shoot on Target             int64
Yellow Cards                int64
Red Cards                   int64
Touches                     int64
Dribbles                    int64
Tackles                     int64
Blocks                      int64
Expected Goals (xG)       float64
Non-Penalty xG (npxG)     float64
Expected Assists (xAG)    float64
Shot-Creating Actions       int64
Goal-Creating Actions       int64
Passes Completed            int64
Passes Attempted            int64
Pass Completion %          object
Progressive Passes          int64
Carries                     int64
Progressive Carries         int64
Dribble Attempts            int64
Successful Dribbles         int64
Date                       object
dtype: object

### Cantidad total de nulos y porcentaje de nulos por columna

In [5]:
print("Porcentaje de nulos por columna:")
display((df.isnull().mean() * 100).round(2))

print("Nulos totales:", df.isnull().sum().sum())

Porcentaje de nulos por columna:

Player                    0.00
Team                      0.00
#                         0.00
Nation                    0.00
Position                  0.00
Age                       0.00
Minutes                   0.14
Goals                     0.00
Assists                   0.00
Penalty Shoot on Goal     0.00
Penalty Shoot             0.00
Total Shoot               0.00
Shoot on Target           0.00
Yellow Cards              0.00
Red Cards                 0.00
Touches                   0.00
Dribbles                  0.00
Tackles                   0.00
Blocks                    0.00
Expected Goals (xG)       0.00
Non-Penalty xG (npxG)     0.00
Expected Assists (xAG)    0.00
Shot-Creating Actions     0.00
Goal-Creating Actions     0.00
Passes Completed          0.00
Passes Attempted          0.00
Pass Completion %         1.08
Progressive Passes        0.00
Carries                   0.00
Progressive Carries       0.00
Dribble Attempts          0.00
Successful Dribbles       0.00
Date                      0.00
dtype: float64

Nulos totales: 52

### Limpieza de los datos

In [6]:
eda = ProcesadorEDA(df)
df_clean = eda.limpieza_datos()

df_clean.head()

 PROCESO DE EDA
✔ Posiciones transformadas a columnas dummies: ['AM', 'CB', 'CM', 'DM', 'FW', 'GK', 'LB', 'LM', 'LW', 'RB', 'RM', 'RW', 'WB']
✔ Normalizado Pass Completion %
✔ Convertida columna Date a datetime
✔ Archivo limpio guardado en: src/data/processed/premier_clean.csv

,Player,Team,#,Nation,Position,Age,Minutes,Goals,Assists,Penalty Shoot on Goal,...,POS_DM,POS_FW,POS_GK,POS_LB,POS_LM,POS_LW,POS_RB,POS_RM,POS_RW,POS_WB
0,Bruno Fernandes,Manchester United,8,POR,"FW,AM",29,90.0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,Marcus Rashford,Manchester United,10,ENG,LW,26,90.0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,Amad Diallo,Manchester United,16,CIV,RW,22,82.5,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,Alejandro Garnacho,Manchester United,17,ARG,RW,20,30.0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,Mason Mount,Manchester United,7,ENG,AM,25,60.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Verificación de AGE(edad)

In [7]:
df_clean["Age"].describe()

count    4270.000000
mean       26.000703
std         3.923818
min        17.000000
25%        23.000000
50%        26.000000
75%        28.000000
max        39.000000
Name: Age, dtype: float64

###  Listar columnas dummies de Position(disyuntiva para las posiciones que juegan los jugadores)

In [8]:
[pos for pos in df_clean.columns if pos.startswith("POS_")]

['POS_AM',
 'POS_CB',
 'POS_CM',
 'POS_DM',
 'POS_FW',
 'POS_GK',
 'POS_LB',
 'POS_LM',
 'POS_LW',
 'POS_RB',
 'POS_RM',
 'POS_RW',
 'POS_WB']

Conteo por posiciones(usando dummies)

In [9]:
df_clean[[c for c in df_clean.columns if c.startswith("POS_")]].sum().sort_values(ascending=False)

POS_CB    713
POS_FW    545
POS_DM    521
POS_CM    441
POS_LW    419
POS_RW    397
POS_RB    373
POS_AM    372
POS_LB    367
POS_GK    283
POS_LM    231
POS_RM    226
POS_WB     78
dtype: int64

### Fecha min y max

In [10]:
df_clean["Date"].describe()

count                             4270
mean     2024-10-11 23:28:17.985948416
min                2024-08-16 00:00:00
25%                2024-09-14 00:00:00
50%                2024-10-06 00:00:00
75%                2024-11-09 00:00:00
max                2024-12-05 00:00:00
Name: Date, dtype: object

### Resumen estadístico del dataset limpio

In [11]:
eda.resumen_descriptivo()

=== RESUMEN DESCRIPTIVO ===

,Player,Team,#,Nation,Position,Age,Minutes,Goals,Assists,Penalty Shoot on Goal,...,POS_DM,POS_FW,POS_GK,POS_LB,POS_LM,POS_LW,POS_RB,POS_RM,POS_RW,POS_WB
count,4270,4270,4270.000000,4270,4270,4270.000000,4270.000000,4270.000000,4270.000000,4270.000000,...,4270.000000,4270.000000,4270.000000,4270.000000,4270.000000,4270.000000,4270.000000,4270.000000,4270.000000,4270.000000
unique,478,20,NaN,57,164,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Joshua Zirkzee,Fulham,NaN,ENG,CB,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,14,222,NaN,1273,653,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,16.780094,NaN,NaN,26.000703,64.816393,0.094145,0.071194,0.005855,...,0.122014,0.127635,0.066276,0.085948,0.054098,0.098126,0.087354,0.052927,0.092974,0.018267
min,NaN,NaN,1.000000,NaN,NaN,17.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,8.000000,NaN,NaN,23.000000,34.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,15.000000,NaN,NaN,26.000000,82.500000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,24.000000,NaN,NaN,28.000000,90.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,NaN,NaN,87.000000,NaN,NaN,39.000000,90.000000,4.000000,3.000000,3.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
std,NaN,NaN,12.215586,NaN,NaN,3.923818,31.234244,0.326883,0.271362,0.085014,...,0.327340,0.333722,0.248794,0.280321,0.226238,0.297520,0.282386,0.223915,0.290430,0.133931

### Matriz de correlación

In [12]:
correlacion = eda.matriz_correlacion()
correlacion

=== MATRIZ DE CORRELACIÓN ===

,#,Age,Minutes,Goals,Assists,Penalty Shoot on Goal,Penalty Shoot,Total Shoot,Shoot on Target,Yellow Cards,...,POS_DM,POS_FW,POS_GK,POS_LB,POS_LM,POS_LW,POS_RB,POS_RM,POS_RW,POS_WB
#,1.000000,-0.228615,-0.083881,-0.056645,-0.000293,-0.019963,-0.024004,-0.037795,-0.063170,0.003167,...,0.027215,-0.064021,-0.043838,0.046429,0.029056,-0.010303,0.088417,0.051358,0.025308,-0.017160
Age,-0.228615,1.000000,0.114967,-0.006078,-0.012367,0.035099,0.029574,-0.054422,-0.047172,0.009665,...,0.041150,0.006729,0.213270,-0.069482,-0.069178,-0.086140,0.037152,-0.076827,-0.095228,-0.009831
Minutes,-0.083881,0.114967,1.000000,0.107151,0.081884,0.030222,0.032700,0.235836,0.161886,0.117042,...,-0.007637,-0.094407,0.206697,0.055110,-0.072352,-0.092462,0.053329,-0.046472,-0.056387,0.017657
Goals,-0.056645,-0.006078,0.107151,1.000000,0.080227,0.308903,0.286303,0.419063,0.598466,-0.019094,...,-0.046082,0.186153,-0.076741,-0.052537,0.000800,0.063956,-0.053586,0.008715,0.055823,-0.023239
Assists,-0.000293,-0.012367,0.081884,0.080227,1.000000,0.042851,0.053878,0.137699,0.078735,0.015879,...,-0.013429,0.016035,-0.062967,-0.003475,0.021192,0.041112,-0.010869,0.038205,0.079465,0.009325
Penalty Shoot on Goal,-0.019963,0.035099,0.030222,0.308903,0.042851,1.000000,0.914918,0.065017,0.064359,-0.000293,...,-0.025676,0.056220,-0.018350,-0.021121,-0.016472,-0.022719,-0.021309,0.008329,0.053846,-0.009395
Penalty Shoot,-0.024004,0.029574,0.032700,0.286303,0.053878,0.914918,1.000000,0.063191,0.059854,-0.000063,...,-0.013743,0.068392,-0.020842,-0.023989,-0.007553,-0.025804,-0.024203,0.004049,0.044474,-0.010671
Total Shoot,-0.037795,-0.054422,0.235836,0.419063,0.137699,0.065017,0.063191,1.000000,0.703255,-0.003627,...,-0.042907,0.220378,-0.185642,-0.099427,0.047047,0.119335,-0.083471,0.051194,0.145058,-0.015124
Shoot on Target,-0.063170,-0.047172,0.161886,0.598466,0.078735,0.064359,0.059854,0.703255,1.000000,0.011777,...,-0.060937,0.227596,-0.126191,-0.081069,0.034157,0.091913,-0.074871,0.028620,0.110303,-0.017040
Yellow Cards,0.003167,0.009665,0.117042,-0.019094,0.015879,-0.000293,-0.000063,-0.003627,0.011777,1.000000,...,0.072384,-0.047072,-0.052216,0.001555,-0.014758,-0.077315,0.006049,-0.001455,-0.000328,-0.002827
Red Cards,-0.020935,0.032412,-0.028100,0.000235,-0.018447,-0.004842,-0.005500,-0.003334,-0.001159,0.130829,...,0.024933,-0.016858,-0.018730,-0.021558,0.012785,-0.011936,0.001963,-0.001667,-0.010980,-0.009590
Touches,-0.052464,0.074039,0.741140,-0.007935,0.060334,-0.012526,-0.012095,0.117466,0.034166,0.107310,...,0.069959,-0.297921,-0.001638,0.131245,-0.060527,-0.141674,0.127040,-0.063081,-0.122567,0.035181
Dribbles,0.031811,-0.054535,0.320848,-0.008346,0.038385,-0.012580,-0.016946,0.048659,0.005692,0.063956,...,0.176666,-0.176072,-0.212624,0.116144,-0.011056,-0.056146,0.130179,0.007614,-0.034025,0.079585
Tackles,0.013411,0.002179,0.290688,-0.028685,0.003177,-0.027076,-0.034169,-0.005269,-0.040697,0.083796,...,0.115620,-0.170159,-0.157408,0.116602,-0.030012,-0.099296,0.095828,-0.035348,-0.080736,0.018187
Blocks,-0.038920,-0.065339,0.302043,0.004687,0.015706,-0.009699,-0.012491,0.046412,0.022625,0.077119,...,0.083756,-0.121573,-0.190543,0.046225,-0.005023,-0.046755,0.029343,-0.002300,-0.038953,0.033964
Expected Goals (xG),-0.048859,-0.008515,0.158085,0.614235,0.112933,0.368567,0.392172,0.672679,0.630402,-0.018593,...,-0.076053,0.294267,-0.119339,-0.095189,0.019219,0.065701,-0.084926,0.011204,0.090792,-0.024997
Non-Penalty xG (npxG),-0.043898,-0.020027,0.159546,0.561191,0.102226,0.064539,0.057218,0.706751,0.661912,-0.020469,...,-0.077466,0.294458,-0.121823,-0.094864,0.023137,0.080851,-0.083229,0.011184,0.082905,-0.023186
Expected Assists (xAG),-0.006133,-0.023830,0.162523,0.136403,0.549552,0.101858,0.104834,0.249408,0.152203,-0.001171,...,-0.006683,0.008794,-0.109753,0.021960,0.043648,0.101266,-0.024461,0.062615,0.110458,0.025561
Shot-Creating Actions,-0.006047,-0.052197,0.305770,0.157957,0.317086,0.058278,0.059777,0.465878,0.303151,0.029098,...,0.061657,-0.002334,-0.196902,0.027691,0.067574,0.130159,-0.018206,0.106439,0.123814,0.025602
Goal-Creating Actions,-0.004724,-0.026128,0.124832,0.166055,0.703692,0.095290,0.098313,0.175250,0.135656,0.007208,...,0.013074,0.023564,-0.088490,-0.007339,0.028455,0.048689,-0.019956,0.055768,0.072163,0.007752
Passes Completed,-0.047419,0.085198,0.630496,-0.053334,0.035172,-0.027391,-0.026182,0.017053,-0.035238,0.094634,...,0.086006,-0.312443,0.012280,0.123735,-0.068058,-0.158891,0.114419,-0.079997,-0.160720,0.014267
Passes Attempted,-0.049475,0.097883,0.682906,-0.045465,0.046284,-0.019038,-0.018359,0.039292,-0.023239,0.096175,...,0.070044,-0.318867,0.052546,0.132906,-0.064719,-0.156599,0.127835,-0.072853,-0.144767,0.024483
Pass Completion %,0.019657,-0.013086,0.115719,-0.060445,-0.000250,-0.042712,-0.040411,-0.074036,-0.066742,0.031037,...,0.129275,-0.194501,-0.077575,0.038365,-0.027807,-0.058693,0.030911,-0.046254,-0.133644,-0.008919
Progressive Passes,0.008509,-0.000530,0.391948,0.040350,0.127738,0.018660,0.021010,0.216446,0.110467,0.073082,...,0.136126,-0.169138,-0.235609,0.092997,0.028137,-0.044488,0.087260,0.037680,-0.049970,-0.010564
Carries,-0.048557,0.050790,0.660058,0.008421,0.070543,-0.006068,-0.007604,0.132283,0.056927,0.086998,...,0.038114,-0.263063,0.038248,0.057704,-0.032094,-0.081300,0.049616,-0.040028,-0.069721,0.004721
Progressive Carries,0.021848,-0.144202,0.226174,0.135136,0.177571,0.025185,0.026770,0.385734,0.276790,0.007102,...,-0.080118,-0.021841,-0.187105,0.043324,0.136094,0.241929,0.013598,0.094832,0.236015,0.049243
Dribble Attempts,0.011905,-0.182432,0.219582,0.117293,0.143849,0.021509,0.022171,0.324617,0.244134,0.012232,...,-0.049898,0.026314,-0.180537,-0.011148,0.121889,0.256442,-0.023585,0.123802,0.233888,0.056370
Successful Dribbles,0.005387,-0.137745,0.197028,0.091188,0.120826,0.016207,0.009085,0.260567,0.197926,0.021494,...,-0.011752,-0.008466,-0.137668,-0.000611,0.109392,0.198171,-0.013690,0.088454,0.154243,0.047924
POS_AM,-0.002801,-0.053395,-0.075735,0.048219,0.084215,0.037339,0.029523,0.141148,0.091526,-0.011359,...,-0.041583,-0.060924,-0.082304,-0.088804,-0.029826,-0.026528,-0.095574,-0.035938,-0.015975,-0.004932
POS_CB,-0.113165,0.046494,0.197432,-0.080931,-0.085077,-0.030837,-0.035025,-0.133642,-0.113597,0.041639,...,-0.159229,-0.167489,-0.119281,-0.099204,-0.107071,-0.147680,-0.082915,-0.105840,-0.139018,-0.042315
POS_CM,0.047819,0.013473,-0.032354,-0.036537,-0.012470,-0.014322,-0.018257,-0.001834,-0.025297,0.052993,...,0.096850,-0.118280,-0.090416,-0.098575,0.020897,-0.101596,-0.088641,-0.011484,-0.090105,-0.046293
POS_DM,0.027215,0.041150,-0.007637,-0.046082,-0.013429,-0.025676,-0.013743,-0.042907,-0.060937,0.072384,...,1.000000,-0.140448,-0.099319,-0.111760,-0.079663,-0.113344,-0.100127,-0.075344,-0.109497,-0.050851
POS_FW,-0.064021,0.006729,-0.094407,0.186153,0.016035,0.056220,0.068392,0.220378,0.227596,-0.047072,...,-0.140448,1.000000,-0.101907,-0.114788,-0.066655,-0.055392,-0.118338,-0.027728,-0.083794,-0.052176
POS_GK,-0.043838,0.213270,0.206697,-0.076741,-0.062967,-0.018350,-0.020842,-0.185642,-0.126191,-0.052216,...,-0.099319,-0.101907,1.000000,-0.081697,-0.063715,-0.087880,-0.082425,-0.062982,-0.085299,-0.036342
POS_LB,0.046429,-0.069482,0.055110,-0.052537,-0.003475,-0.021121,-0.023989,-0.099427,-0.081069,0.001555,...,-0.111760,-0.114788,-0.081697,1.000000,-0.047478,-0.089913,-0.006092,-0.057563,-0.089544,0.033044
POS_LM,0.029056,-0.069178,-0.072352,0.000800,0.021192,-0.016472,-0.007553,0.047047,0.034157,-0.014758,...,-0.079663,-0.066655,-0.063715,-0.047478,1.000000,0.032479,-0.070321,0.031322,-0.048046,-0.001698
POS_LW,-0.010303,-0.086140,-0.092462,0.063956,0.041112,-0.022719,-0.025804,0.119335,0.091913,-0.077315,...,-0.113344,-0.055392,-0.087880,-0.089913,0.032479,1.000000,-0.093685,-0.035783,0.051626,-0.033237
POS_RB,0.088417,0.037152,0.053329,-0.053586,-0.010869,-0.021309,-0.024203,-0.083471,-0.074871,0.006049,...,-0.100127,-0.118338,-0.082425,-0.006092,-0.070321,-0.093685,1.000000,-0.036091,-0.084770,0.025929
POS_RM,0.051358,-0.076827,-0.046472,0.008715,0.038205,0.008329,0.004049,0.051194,0.028620,-0.001455,...,-0.075344,-0.027728,-0.062982,-0.057563,0.031322,-0.035783,-0.036091,1.000000,0.050385,-0.016625
POS_RW,0.025308,-0.095228,-0.056387,0.055823,0.079465,0.053846,0.044474,0.145058,0.110303,-0.000328,...,-0.109497,-0.083794,-0.085299,-0.089544,-0.048046,0.051626,-0.084770,0.050385,1.000000,-0.013562
POS_WB,-0.017160,-0.009831,0.017657,-0.023239,0.009325,-0.009395,-0.010671,-0.015124,-0.017040,-0.002827,...,-0.050851,-0.052176,-0.036342,0.033044,-0.001698,-0.033237,0.025929,-0.016625,-0.013562,1.000000

### Variables más correlacionadas

In [14]:
cor = correlacion.abs().unstack().sort_values(ascending=False)
cor[cor < 1].head(10)

Passes Attempted       Passes Completed         0.984732
Passes Completed       Passes Attempted         0.984732
Touches                Passes Attempted         0.984226
Passes Attempted       Touches                  0.984226
Passes Completed       Touches                  0.963423
Touches                Passes Completed         0.963423
Non-Penalty xG (npxG)  Expected Goals (xG)      0.940718
Expected Goals (xG)    Non-Penalty xG (npxG)    0.940718
Carries                Passes Attempted         0.936971
Passes Attempted       Carries                  0.936971
dtype: float64